version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_api
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__DefaultConnection: "Host=database;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword"
    depends_on:
      - database

  database:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
